development:
  adapter: mysql2
  database: rongyi_term_cms_development
  user: root
  password: 
  pool: 5
  timeout: 5000
test:
  adapter: mysql2
  database: rongyi_term_cms_test
  user: root
  password: 
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: rongyi_term_cms_production
  user: root
  password: 
  pool: 5
  timeout: 5000
